### ISSUE TITLE
Installation fails on ubuntu 20.04 with python3

### ISSUE THREAD

**Issue by maxipalay** [svpcom/wifibroadcast#136]
**Describe the bug**
Installation fails on ubuntu Focal (20.04).

**To Reproduce**
Installation steps until executing make deb.

**Screenshots**
![image](https://user-images.githubusercontent.com/41023326/119593331-366dee80-bdb0-11eb-812e-c7431e2f3545.png)

**Your setup (please complete the following information):**
 - Ubuntu 20.04
 - Hardware: Rpi 4

**Comment by maxipalay** [comment]
Seems the issue is in wifibroadcast/version.py

I don't have python2 installed and the env in version.py is /usr/bin/env python.

Changing it to /usr/bin/env python3 solved the issue.

Leaving here for documentation purposes.

**Comment by AlexNester-QuadX** [comment]
Have the same problem.
But I havn't any env python or env python3 in /usr/bin/

just only env but if I change to #!/usr/bin/env its no work
any installation like

sudo apt-get install python-is-python3

sudo apt install python-minimal


system
 Ubuntu 22.04.3 LTS
(ubuntu under Windows)


`sudo ./scripts/install_gs.sh wifi0
Hit:1 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:2 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:3 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:4 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:5 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
build-essential is already the newest version (12.9ubuntu3).
debhelper is already the newest version (13.6ubuntu1).
iw is already the newest version (5.16-1build1).
libpcap-dev is already the newest version (1.10.1-4build1).
libsodium-dev is already the newest version (1.0.18-1build2).
python3-serial is already the newest version (3.5-1).
dh-python is already the newest version (5.20220403).
virtualenv is already the newest version (20.13.0+ds-2).
python3-all is already the newest version (3.10.6-1~22.04).
python3-future is already the newest version (0.18.2-5ubuntu0.1).
python3-pyroute2 is already the newest version (0.6.4-3ubuntu2).
python3-twisted is already the newest version (22.1.0-2ubuntu2.3).
python3-pip is already the newest version (22.0.2+dfsg-1ubuntu0.3).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
rm -rf deb_dist
/home/t0968639585/wfb-ng/env/bin/python ./setup.py --command-packages=stdeb.command bdist_deb
running bdist_deb
running sdist_dsc
running egg_info
writing wfb_ng.egg-info/PKG-INFO
writing dependency_links to wfb_ng.egg-info/dependency_links.txt
writing entry points to wfb_ng.egg-info/entry_points.txt
writing top-level names to wfb_ng.egg-info/top_level.txt
reading manifest file 'wfb_ng.egg-info/SOURCES.txt'
adding license file 'LICENSE.txt'
writing manifest file 'wfb_ng.egg-info/SOURCES.txt'
running sdist
running check
creating wfb-ng-23.8.14.60981
creating wfb-ng-23.8.14.60981/scripts
creating wfb-ng-23.8.14.60981/scripts/default
creating wfb-ng-23.8.14.60981/wfb_ng
creating wfb-ng-23.8.14.60981/wfb_ng.egg-info
creating wfb-ng-23.8.14.60981/wfb_ng/conf
copying files to wfb-ng-23.8.14.60981...
copying LICENSE.txt -> wfb-ng-23.8.14.60981
copying README.md -> wfb-ng-23.8.14.60981
copying setup.py -> wfb-ng-23.8.14.60981
copying wfb_keygen -> wfb-ng-23.8.14.60981
copying wfb_rx -> wfb-ng-23.8.14.60981
copying wfb_tx -> wfb-ng-23.8.14.60981
copying scripts/98-wifibroadcast.conf -> wfb-ng-23.8.14.60981/scripts
copying scripts/wifibroadcast -> wfb-ng-23.8.14.60981/scripts
copying scripts/wifibroadcast.service -> wfb-ng-23.8.14.60981/scripts
copying scripts/wifibroadcast@.service -> wfb-ng-23.8.14.60981/scripts
copying scripts/default/wifibroadcast -> wfb-ng-23.8.14.60981/scripts/default
copying wfb_ng/__init__.py -> wfb-ng-23.8.14.60981/wfb_ng
copying wfb_ng/cli.py -> wfb-ng-23.8.14.60981/wfb_ng
copying wfb_ng/common.py -> wfb-ng-23.8.14.60981/wfb_ng
copying wfb_ng/config_parser.py -> wfb-ng-23.8.14.60981/wfb_ng
copying wfb_ng/latency_test.py -> wfb-ng-23.8.14.60981/wfb_ng
copying wfb_ng/mavlink.py -> wfb-ng-23.8.14.60981/wfb_ng
copying wfb_ng/mavlink_protocol.py -> wfb-ng-23.8.14.60981/wfb_ng
copying wfb_ng/proxy.py -> wfb-ng-23.8.14.60981/wfb_ng
copying wfb_ng/server.py -> wfb-ng-23.8.14.60981/wfb_ng
copying wfb_ng/tuntap.py -> wfb-ng-23.8.14.60981/wfb_ng
copying wfb_ng.egg-info/PKG-INFO -> wfb-ng-23.8.14.60981/wfb_ng.egg-info
copying wfb_ng.egg-info/SOURCES.txt -> wfb-ng-23.8.14.60981/wfb_ng.egg-info
copying wfb_ng.egg-info/dependency_links.txt -> wfb-ng-23.8.14.60981/wfb_ng.egg-info
copying wfb_ng.egg-info/entry_points.txt -> wfb-ng-23.8.14.60981/wfb_ng.egg-info
copying wfb_ng.egg-info/not-zip-safe -> wfb-ng-23.8.14.60981/wfb_ng.egg-info
copying wfb_ng.egg-info/top_level.txt -> wfb-ng-23.8.14.60981/wfb_ng.egg-info
copying wfb_ng/conf/__init__.py -> wfb-ng-23.8.14.60981/wfb_ng/conf
copying wfb_ng/conf/master.cfg -> wfb-ng-23.8.14.60981/wfb_ng/conf
copying wfb_ng/conf/site.cfg -> wfb-ng-23.8.14.60981/wfb_ng/conf
Writing wfb-ng-23.8.14.60981/setup.cfg
Creating tar archive
removing 'wfb-ng-23.8.14.60981' (and everything under it)
dpkg-buildpackage: info: source package wfb-ng
dpkg-buildpackage: info: source version 23.8.14.60981-1
dpkg-buildpackage: info: source distribution unstable
dpkg-buildpackage: info: source changed by Vasily Evseenko <svpcom@p2ptech.org>
 dpkg-source --before-build .
dpkg-source: info: using options from wfb-ng-23.8.14.60981/debian/source/options: --extend-diff-ignore=\.egg-info$
 debian/rules clean
make[1]: Entering directory '/home/t0968639585/wfb-ng/deb_dist/wfb-ng-23.8.14.60981'
dh clean --with python3 --buildsystem=python_distutils
dh: warning: Compatibility levels before 10 are deprecated (level 9 in use)
   debian/rules override_dh_auto_clean
make[2]: Entering directory '/home/t0968639585/wfb-ng/deb_dist/wfb-ng-23.8.14.60981'
python3 setup.py clean -a
running clean
'build/lib' does not exist -- can't clean it
'build/bdist.linux-x86_64' does not exist -- can't clean it
'build/scripts-3.10' does not exist -- can't clean it
find . -name \*.pyc -exec rm {} \;
make[2]: Leaving directory '/home/t0968639585/wfb-ng/deb_dist/wfb-ng-23.8.14.60981'
   dh_clean -O--buildsystem=python_distutils
dh_clean: warning: Compatibility levels before 10 are deprecated (level 9 in use)
make[1]: Leaving directory '/home/t0968639585/wfb-ng/deb_dist/wfb-ng-23.8.14.60981'
 dpkg-source -b .
dpkg-source: info: using options from wfb-ng-23.8.14.60981/debian/source/options: --extend-diff-ignore=\.egg-info$
dpkg-source: info: using source format '3.0 (quilt)'
dpkg-source: info: building wfb-ng using existing ./wfb-ng_23.8.14.60981.orig.tar.gz
dpkg-source: info: building wfb-ng in wfb-ng_23.8.14.60981-1.debian.tar.xz
dpkg-source: info: building wfb-ng in wfb-ng_23.8.14.60981-1.dsc
 dpkg-genbuildinfo --build=source -O../wfb-ng_23.8.14.60981-1_source.buildinfo
 dpkg-genchanges -sa --build=source -O../wfb-ng_23.8.14.60981-1_source.changes
dpkg-genchanges: info: including full source code in upload
 dpkg-source --after-build .
dpkg-source: info: using options from wfb-ng-23.8.14.60981/debian/source/options: --extend-diff-ignore=\.egg-info$
dpkg-buildpackage: info: source-only upload (original source is included)
dpkg-source: warning: extracting unsigned source package (wfb-ng_23.8.14.60981-1.dsc)
dpkg-source: info: extracting wfb-ng in wfb-ng-23.8.14.60981
dpkg-source: info: unpacking wfb-ng_23.8.14.60981.orig.tar.gz
dpkg-source: info: unpacking wfb-ng_23.8.14.60981-1.debian.tar.xz
dpkg-buildpackage: warning: using a gain-root-command while being root
dpkg-buildpackage: info: source package wfb-ng
dpkg-buildpackage: info: source version 23.8.14.60981-1
dpkg-buildpackage: info: source distribution unstable
dpkg-buildpackage: info: source changed by Vasily Evseenko <svpcom@p2ptech.org>
dpkg-buildpackage: info: host architecture amd64
 dpkg-source --before-build .
dpkg-source: info: using options from wfb-ng-23.8.14.60981/debian/source/options: --extend-diff-ignore=\.egg-info$
 fakeroot debian/rules clean
fakeroot, while creating message channels: Function not implemented
This may be due to a lack of SYSV IPC support.
fakeroot: error while starting the `faked' daemon.
/usr/bin/fakeroot: 1: kill: Usage: kill [-s sigspec | -signum | -sigspec] [pid | job]... or
kill -l [exitstatus]
dpkg-buildpackage: error: fakeroot debian/rules clean subprocess returned exit status 1
Traceback (most recent call last):
  File "/home/t0968639585/wfb-ng/./setup.py", line 39, in <module>
    setup(
  File "/home/t0968639585/wfb-ng/env/lib/python3.10/site-packages/setuptools/__init__.py", line 103, in setup
    return distutils.core.setup(**attrs)
  File "/home/t0968639585/wfb-ng/env/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/home/t0968639585/wfb-ng/env/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/home/t0968639585/wfb-ng/env/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/home/t0968639585/wfb-ng/env/lib/python3.10/site-packages/setuptools/dist.py", line 989, in run_command
    super().run_command(command)
  File "/home/t0968639585/wfb-ng/env/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/t0968639585/wfb-ng/env/lib/python3.10/site-packages/stdeb/command/bdist_deb.py", line 67, in run
    util.process_command(syscmd, cwd=target_dirs[0])
  File "/home/t0968639585/wfb-ng/env/lib/python3.10/site-packages/stdeb/util.py", line 226, in process_command
    check_call(args, cwd=cwd)
  File "/home/t0968639585/wfb-ng/env/lib/python3.10/site-packages/stdeb/util.py", line 59, in check_call
    raise CalledProcessError(retcode)
stdeb.util.CalledProcessError: 1
make: *** [Makefile:50: deb] Error 1
t0968639585@DESKTOP-V36GQNC:~/wfb-ng$`
